server:
  port: 8081
  servlet:
    context-path: /LeaveWord

spring:
  profiles:
    active: @spring.active@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false


