apiVersion: v1
kind: Service
metadata:
  name: leaveword-service
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: leaveword